
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTMASTER_H
#define TESTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestMaster_Data;
extern UNS32 pdo_s2m_rx_data;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 pdo_m2s_tx_data;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 sdo_s2m_rx_array[10];		/* Mapped at index 0x2002, subindex 0x01 - 0x0A */
extern UNS32 sdo_m2s_tx_array[10];		/* Mapped at index 0x2003, subindex 0x01 - 0x0A */

#endif // TESTMASTER_H
